apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}

type: Opaque

stringData:
  username: {{ randAlphaNum 12 | quote }}
  password: {{ randAlphaNum 20 | quote }}
  api-key: {{ randAlphaNum 32 | quote }}