apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: payment-api-pvc
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: payment-worker-pvc
  namespace: {{ .Values.namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi