apiVersion: v1
kind: Service
metadata:
  name: payment-worker-service
  namespace: {{ .Values.namespace }}

spec:
  type: ClusterIP

  selector:
    app: payment-worker

  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP

  