apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-worker
spec:
  replicas: {{ .Values.api.replicaCount }}

  selector:
    matchLabels:
      app: payment-worker

  template:
    metadata:
      labels:
        app: payment-worker

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: payment-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}

          ports:
            - name: http
              containerPort: 8080

          envFrom:
            - configMapRef:
                name: payment-config

            - secretRef:
                name: payment-secret

          resources:
{{ toYaml .Values.api.resources  | indent 12 }}
  
          securityContext:
            allowPrivilageEscalation: false

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5