apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: nginx-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

            - name: nginx-secret-volume
              mountPath: /etc/nginx/auth

            - name: nginx-storage
              mountPath: /usr/share/nginx/html

            - name: nginx-index-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html

      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            optional: false

        - name: nginx-secret-volume
          secret:
            secretName: nginx-secret
            optional: false

        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

        - name: nginx-index-volume
          configMap:
            name: nginx-config
