apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: postgres-secret
  namespace: external-secrets

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: postgres-secret

  dataFrom:
    - extract:
        key: finpay-postgres