apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: "{{ .Values.namespace }}"

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: "{{ .Values.image.pullPolicy }}"

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

            - name: nginx-secret-volume
              mountPath: /etc/nginx/auth

            - name: nginx-storage
              mountPath: /usr/share/nginx/html

            - name: nginx-index-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
        - name: stress-test
          image: polinux/stress

          command:
            - stress

          args:
            - --cpu
            - "1"
            - --timeout
            - "300s"
          
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"

            limits:
              cpu: "200m"
              memory: "128Mi"  

      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            optional: false

        - name: nginx-secret-volume
          secret:
            secretName: nginx-secret
            optional: false

        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pvc

        - name: nginx-index-volume
          configMap:
            name: nginx-config