apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: "{{ .Values.namespace }}"

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: "{{ .Values.image.pullPolicy }}"

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}

          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}

          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}

      volumes:
{{ toYaml .Values.volumes | indent 8 }}