apiVersion: v1
kind: Secret

metadata:
  name: nginx-secret
  namespace: "{{ .Values.namespace }}"

type: Opaque

stringData:
  .htpasswd: |
    {{ htpasswd .Values.auth.username .Values.auth.password }}
