# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cloud-academy-tf-state-payment-app"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "live/dev/vpc/terraform.tfstate"
    region         = "eu-central-1"
  }
}
