# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-central-1"

  default_tags {
    tags = {
      project    = "payment-app"
      managed_by = "terragrunt"
    }
  }
}
